services:
  portainer:
    image: portainer/portainer-ce:2.27.9
    container_name: portainer
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer_password:/tmp/portainer_password
      - portainer_data:/data
    command: --admin-password-file /tmp/portainer_password

  portainer_agent:
    image: portainer/agent:2.27.9
    container_name: portainer_agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      
volumes:
  portainer_data: